# -*- coding: utf-8 -*-
"""Day 20 - Web Scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ha9oLborbDZacKRIIGHo72OvnWjjb3xj
"""

!apt update

!apt install chromium-chromedriver

!pip install selenium

!wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && apt install ./google-chrome-stable_current_amd64.deb

from selenium import webdriver
from bs4 import BeautifulSoup

def driversetup():
    options = webdriver.ChromeOptions()
    #run Selenium in headless mode
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    #overcome limited resource problems
    options.add_argument('--disable-dev-shm-usage')
    # options.add_argument("lang=en")
    #open Browser in maximized mode
    # options.add_argument("start-maximized")
    #disable infobars
    # options.add_argument("disable-infobars")
    #disable extension
    # options.add_argument("--disable-extensions")
    # options.add_argument("--incognito")
    # options.add_argument("--disable-blink-features=AutomationControlled")

    driver = webdriver.Chrome(options=options)

    # driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined});")

    return driver

# init driver and get data from 'https://dibimbing.id/layanan/bootcamp'
url = 'https://dibimbing.id/layanan/bootcamp'
driver = driversetup()
driver.get(url)
soup = BeautifulSoup(driver.page_source, 'html.parser')
driver.close()

# find Bootcamp title using argument ('p',{"class": "text-black max-w-[108px] font-bold text-sm lg:text-base"}) and use findAll chain function
page = soup.findAll('p',{"class": "text-black max-w-[108px] font-bold text-sm lg:text-base"})

bootcamp_title = []
for title in page:
  bootcamp_title.append(title.get_text())

# find Bootcamp desc using argument ('p',{"class": "text-xs md:text-sm text-center text-grey600"}) and use findAll chain function
page = soup.findAll('p',{"class": "text-xs md:text-sm text-center text-grey600"})

bootcamp_desc = []
for desc in page:
  bootcamp_desc.append(desc.get_text())

!pip install numpy pandas

import numpy as np

# Convert the arrays to NumPy arrays
numpy_bootcamp_title = np.array(bootcamp_title)
numpy_bootcamp_desc = np.array(bootcamp_desc)

# Combine the arrays horizontally (along columns) using np.column_stack
combined_array = np.column_stack((numpy_bootcamp_title, numpy_bootcamp_desc))

# Create a Pandas DataFrame from the combined NumPy array (optional)
import pandas as pd
combined_df = pd.DataFrame(combined_array, columns=['Title', 'Description'])

import time
# Specify the CSV file path
csv_file_path = 'data_bootcamp_dibimbing_'+str(time.time())+'.csv'

# Write the DataFrame to the CSV file
combined_df.to_csv(csv_file_path, index=False)

print(f'CSV file "{csv_file_path}" has been created.')

# # or
# print(combined_df)